import{useState}from'react';
import{api}from'./api.js';
import{WorkbenchContext,useRequest,useAction,ErrorNotice,Empty,type PageName}from'./common.js';
import{Review}from'./Review.js';import{Weakness}from'./Weakness.js';import{Plans}from'./Plans.js';
import{Bank}from'./Bank.js';import{Today}from'./Today.js';import{Settings}from'./Settings.js';
export function App({onExit}:{onExit:()=>void}){
 const bootstrap=useRequest('bootstrap',{}),[page,setPage]=useState<PageName>('today'),[accountId,setAccountId]=useState<string|null>(null),[problemKey,setProblemKey]=useState<string|null>(null);
 const [selectedKeys,setSelectedKeys]=useState<string[]>([]);
 const [adding,setAdding]=useState(false),[platform,setPlatform]=useState<'codeforces'|'luogu'>('codeforces'),[handle,setHandle]=useState(''),action=useAction();
 const navigate=(next:PageName,key?:string)=>{setPage(next);if(key!==undefined)setProblemKey(key);};
 return <div className="icpc-root"><header className="icpc-header"><div className="icpc-brand"><span className="icpc-mark">IC</span><div><strong>ICPC 训练</strong><small>每一步都有依据</small></div></div><div className="icpc-header-actions"><label className="icpc-account">当前账号<select aria-label="当前账号" value={accountId??''} onChange={e=>{setAccountId(e.target.value||null);setProblemKey(null);setSelectedKeys([]);}}><option value="">未选择账号</option>{bootstrap.data?.accounts.map(a=><option key={a.id} value={a.id}>{a.displayName??a.handle} · {a.sourceInstanceId.split(':')[0]}</option>)}</select></label><button onClick={()=>setAdding(v=>!v)}>{adding?'收起':'添加账号'}</button><button onClick={onExit}>返回对话</button></div></header>
 {adding&&<form className="icpc-add-account" onSubmit={e=>{e.preventDefault();void action.run(async signal=>{await api.request('account.create',{platform,handle},signal);setAdding(false);setHandle('');bootstrap.refresh();return true;});}}><label>平台<select value={platform} onChange={e=>setPlatform(e.target.value as typeof platform)}><option value="codeforces">Codeforces</option><option value="luogu">洛谷</option></select></label><label>{platform==='luogu'?'数字 UID':'Handle'}<input value={handle} onChange={e=>setHandle(e.target.value)} required/></label><button className="icpc-primary" disabled={action.busy||!handle.trim()}>添加</button><span>仅保存公开账号标识，无需密码。</span><ErrorNotice error={action.error}/></form>}
 <nav className="icpc-nav" aria-label="训练工作台">{([['today','今日训练'],['bank','题库'],['review','标签审核'],['weakness','薄弱项'],['plans','训练计划'],['settings','设置']] as const).map(([id,title])=><button key={id} aria-current={page===id?'page':undefined} onClick={()=>navigate(id)}>{title}</button>)}<span>{bootstrap.data?.settings.value.provider??'正在连接'} · max</span></nav>
 <main className="icpc-content"><ErrorNotice error={bootstrap.error}/>{Boolean(bootstrap.error)&&<button onClick={bootstrap.refresh}>重试连接</button>}{bootstrap.pending&&!bootstrap.data&&<Empty>正在加载训练工作台…</Empty>}{bootstrap.data&&<WorkbenchContext.Provider value={{boot:bootstrap.data,accountId,refresh:bootstrap.refresh,navigate,problemKey,selectedKeys,setSelectedKeys}}><div key={accountId??'anonymous'}>{page==='settings'?<Settings/>:page==='bank'?<Bank/>:page==='review'?<Review/>:page==='weakness'?<Weakness/>:page==='plans'?<Plans/>:<Today/>}</div></WorkbenchContext.Provider>}</main><footer className="icpc-footer">本地数据 · 证据复核 · 原始标签与人工判断分别保留</footer>
 </div>;
}