import {useEffect,useState} from 'react';
import type {CoachingLevel} from '../application/coaching-types.js';
import type {ModelCoachingAskRequest} from '../application/model-operation-types.js';
import {api} from './api.js';
import {Notice,ErrorNotice,useAction,useRequest,useWorkbench} from './common.js';
const labels:Record<string,string>={'1':'提示 1：方向','2':'提示 2：关键步骤','3':'提示 3：实现思路',full:'完整讲解与代码'};
const errors:Record<string,string>={manual_statement_needed:'需要先补充完整题面。',snapshot_missing:'需要先建立材料快照。',level_not_earned:'请先完成当前快照的前一级提示。',coaching_quota_exhausted:'已达到最近 24 小时的提示额度。',concurrent_call_active:'另一个提示仍在运行。',settings_changed:'设置已变化，请刷新页面后重新确认。',stale_snapshot:'题目材料已更新，本次结果不用于新快照。',invalid_output:'模型未返回符合约定的结果。',cancelled:'请求已取消；已发生用量仍保留。'};
export function Coaching({problemKey,snapshotId,hasStatement}:{problemKey:string;snapshotId:string|null;hasStatement:boolean}){
 const {accountId,boot}=useWorkbench(),action=useAction(),[storageError,setStorageError]=useState<unknown>(null),[intent,setIntent]=useState<ModelCoachingAskRequest|null>(null),[revealCurrent,setRevealCurrent]=useState(false),[full,setFull]=useState(false),[historyLevel,setHistoryLevel]=useState<CoachingLevel|null>(null),[stale,setStale]=useState(false),[cursor,setCursor]=useState<string|null>(null),[pages,setPages]=useState<(string|null)[]>([]);
 const scope=JSON.stringify([accountId,problemKey,snapshotId]),storageKey='icpc.coaching.intent:'+scope;
 useEffect(()=>{try{const text=sessionStorage.getItem(storageKey);if(text){const v=JSON.parse(text) as ModelCoachingAskRequest;if(v.problemKey===problemKey&&v.accountId===accountId&&typeof v.requestId==='string'&&[1,2,3,'full'].includes(v.level)&&Number.isSafeInteger(v.expectedSettingsRevision))setIntent(v);}}catch(error){setStorageError(Error('无法恢复上次请求标识，请先查看提示历史，避免重复付费。'));}},[storageKey]);
 const status=useRequest('coaching.status',intent?{requestId:intent.requestId,accountId,problemKey,includeResponseText:revealCurrent}:null);
 const history=useRequest('coaching.history',{accountId,problemKey,level:historyLevel,includeResponseText:historyLevel!==null,includeStale:stale,limit:20,cursor});
 const value=status.data,attempt=value?.status==='found'?value.attempt:null,live=value?.operation?.state==='running'||attempt?.status==='reserved';
 useEffect(()=>{if(!live)return;const timer=setInterval(()=>{status.refresh();history.refresh();},1500);return()=>clearInterval(timer);},[live,intent?.requestId]);
 const outcome=value?.operation?.status??(attempt?.status==='settled'?(attempt.error?'failed':'answered'):attempt?.status),code=value?.operation?.errorCode??attempt?.error?.code;
 async function ask(request:ModelCoachingAskRequest){await action.run(async signal=>{sessionStorage.setItem(storageKey,JSON.stringify(request));setIntent(request);setRevealCurrent(true);await api.request('coaching.ask',request,signal);status.refresh();history.refresh();return true;});}
 return <section className="icpc-coaching"><h3>逐级提示</h3><p className="icpc-muted">{boot.settings.value.provider} / {boot.settings.value.coaching.model} · max · 最近 24 小时最多 {boot.settings.value.coaching.maxCallsPer24Hours} 次。提示为未经独立核验的 AI 内容。</p>
 {!hasStatement&&<Notice>当前缺少完整题面，先刷新或手工补充后再请求提示。</Notice>}<ErrorNotice error={action.error??status.error??history.error??storageError}/>
 <div className="icpc-actions">{([1,2,3] as const).map(level=><button key={level} disabled={action.busy||live||!hasStatement||!snapshotId} onClick={()=>void ask({requestId:crypto.randomUUID(),accountId,problemKey,level,expectedSettingsRevision:boot.settings.revision!})}>付费获取{labels[level]}</button>)}</div>
 <label className="icpc-check"><input type="checkbox" checked={full} onChange={e=>setFull(e.target.checked)}/>我明确要查看完整解法和代码</label><button disabled={!full||action.busy||live||!hasStatement||!snapshotId} onClick={()=>void ask({requestId:crypto.randomUUID(),accountId,problemKey,level:'full',explicitFullSolution:true,expectedSettingsRevision:boot.settings.revision!})}>付费生成完整讲解</button>
 {intent&&<Notice><p>{labels[intent.level]} · {live?'生成中':outcome??'等待查询结果'}{code?' · '+(errors[code]??code):''}</p><div className="icpc-actions"><button disabled={action.busy} onClick={()=>{setRevealCurrent(true);status.refresh();}}>读取本次结果（不生成）</button><button disabled={action.busy} onClick={()=>void ask(intent)}>重发同一请求（去重）</button><button disabled={action.busy||!live} onClick={()=>{void action.run(async signal=>{await api.request('coaching.cancel',{requestId:intent.requestId,accountId,problemKey,level:intent.level},signal);status.refresh();history.refresh();return true;});}}>取消生成</button></div>{attempt?.usage&&<p>{attempt.usage.promptTokens} 输入 / {attempt.usage.completionTokens} 输出 tokens</p>}{attempt?.responseText&&<><strong>AI 内容 · 未独立核验</strong><pre>{attempt.responseText}</pre></>}{outcome==='uncertain'&&<p>用量未知，已计入次数。不会自动再付费生成。</p>}</Notice>}
 <details><summary>提示历史（默认不显示正文）</summary><div className="icpc-toolbar"><label>查看某一级正文<select value={historyLevel??''} onChange={e=>{setHistoryLevel(e.target.value===''?null:e.target.value==='full'?'full':Number(e.target.value) as 1|2|3);setCursor(null);setPages([]);}}><option value="">仅查看元数据</option>{Object.entries(labels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label className="icpc-check"><input type="checkbox" checked={stale} onChange={e=>setStale(e.target.checked)}/>同时显示旧快照正文</label><button onClick={history.refresh}>刷新历史</button></div>
 {history.data?.items.map(a=><article key={a.attemptId}><p>{labels[a.level]} · {new Date(a.requestedAt).toLocaleString()} · {a.status} · {a.snapshotState==='current'?'当前材料':'旧材料'}{a.error?' · '+(errors[a.error.code]??a.error.code):''}</p>{a.responseText&&<pre>{a.responseText}</pre>}</article>)}<div className="icpc-actions"><button disabled={!pages.length||history.pending} onClick={()=>{setCursor(pages.at(-1)??null);setPages(pages.slice(0,-1));}}>较新记录</button><button disabled={!history.data?.nextCursor||history.pending} onClick={()=>{setPages([...pages,cursor]);setCursor(history.data!.nextCursor);}}>更早记录</button></div></details>
 </section>;
}
