import {useState} from 'react';
import type {ApiResponse} from '../application/workbench-api.js';
import type {WorkbenchPlanTaskView,WorkbenchPlanView} from '../application/workbench-types.js';
import {api} from './api.js';
import {Panel,Notice,Empty,ErrorNotice,ExternalLink,useAction,useRequest,useWorkbench,tagName} from './common.js';
const kinds={solve:'做题',review:'复习',upskill:'专题提高'} as const;
function PlanTask({task,plan,onChange}:{task:WorkbenchPlanTaskView;plan:WorkbenchPlanView;onChange:()=>void}){
 const {accountId,boot,navigate}=useWorkbench(),action=useAction(),[editing,setEditing]=useState(false),[day,setDay]=useState(task.day),[minutes,setMinutes]=useState(task.minutes),[kind,setKind]=useState(task.kind);
 const valid=Number.isInteger(day)&&day>=1&&day<=plan.horizonDays&&Number.isInteger(minutes)&&minutes>=1&&minutes<=plan.minutesPerDay;
 const cas={planId:plan.planId,accountId:accountId!,expectedHash:plan.contentHash,taskId:task.taskId};
 return <article className="icpc-task"><div className="icpc-toolbar"><strong>第 {task.day} 天 · {task.minutes} 分钟</strong><span className="icpc-tag">{kinds[task.kind]}</span><button onClick={()=>navigate('bank',task.problemKey)}>{task.title}</button><ExternalLink href={task.sourceUrl}>原题</ExternalLink><span>{task.status==='planned'?'待完成':task.status==='done'?'已打卡':'已跳过'}</span></div>
 {task.taxonomyIds&&<p className="icpc-muted">{task.taxonomyIds.map(t=>tagName(t,boot)).join('、')} · {task.rationale}</p>}
 <ErrorNotice error={action.error}/><div className="icpc-actions"><button disabled={action.busy||task.status!=='planned'} onClick={()=>setEditing(v=>!v)}>{editing?'收起编辑':'调整安排'}</button>{plan.status==='adopted'&&(['done','skipped'] as const).map(status=><button key={status} disabled={action.busy||task.status!=='planned'} onClick={()=>{void action.run(async signal=>{await api.request('plan.checkoff',{...cas,status},signal);onChange();return true;});}}>{status==='done'?'完成打卡':'跳过此项'}</button>)}</div>
 {editing&&<form className="icpc-toolbar" onSubmit={e=>{e.preventDefault();void action.run(async signal=>{await api.request('plan.edit',{...cas,patch:{day,minutes,kind}},signal);setEditing(false);onChange();return true;});}}><label>第几天<input type="number" min="1" max={plan.horizonDays} value={day} onChange={e=>setDay(Number(e.target.value))}/></label><label>分钟<input type="number" min="1" max={plan.minutesPerDay} value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label><label>类型<select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}>{Object.entries(kinds).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><button disabled={!valid||action.busy}>保存调整</button></form>}
 </article>;
}
export function Plans(){
 const {accountId,selectedKeys,navigate,boot}=useWorkbench(),action=useAction(),[preview,setPreview]=useState<ApiResponse<'plan.preview'>|null>(null),[id,setId]=useState<string|null>(null),[reveal,setReveal]=useState(false),[days,setDays]=useState(7),[minutes,setMinutes]=useState(60),[estimated,setEstimated]=useState(30),[title,setTitle]=useState('我的训练计划');
 const list=useRequest('plan.list',accountId?{accountId,reveal}:null),detail=useRequest('plan.detail',accountId&&id?{accountId,planId:id,reveal}:null),plan=detail.data;
 const update=()=>{detail.refresh();list.refresh();};
 const valid=[days,minutes,estimated].every(Number.isInteger)&&days>=1&&days<=30&&minutes>=1&&minutes<=1440&&estimated>=1&&estimated<=minutes;
 return <><div className="icpc-page-heading"><div><p className="icpc-eyebrow">TRAINING PLAN</p><h1>把方向变成每天能完成的练习</h1><p>从真实候选题生成规则草案，确认采用后开始打卡。</p></div></div>
 {!accountId?<Empty>请先选择账号，并在题库勾选候选题。</Empty>:<>
 <Panel title="生成计划草案"><p>已选 {selectedKeys.length} 道真实候选题。规则生成不调用模型。</p><ErrorNotice error={action.error}/><form onSubmit={e=>{e.preventDefault();void action.run(async signal=>{const value=await api.request('plan.preview',{accountId,candidateProblemKeys:selectedKeys,title,horizonDays:days,minutesPerDay:minutes,estimatedMinutes:estimated,reveal},signal);setPreview(value);if(value.outcome==='draft')setId(value.plan.planId);list.refresh();return value;});}}><div className="icpc-form-grid"><label>标题<input value={title} maxLength={200} onChange={e=>setTitle(e.target.value)}/></label><label>天数<input type="number" min="1" max="30" value={days} onChange={e=>setDays(Number(e.target.value))}/></label><label>每天分钟<input type="number" min="1" max="1440" value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label><label>每题预计分钟<input type="number" min="1" max={minutes} value={estimated} onChange={e=>setEstimated(Number(e.target.value))}/></label></div><div className="icpc-actions"><button className="icpc-primary" disabled={action.busy||!valid||!title.trim()}>预览规则草案</button><button type="button" onClick={()=>navigate('bank')}>选择候选题</button></div></form>
 {preview?.outcome==='insufficient_evidence'&&<Notice>没有足够的有效候选题，未保存计划。可先练习：{preview.beginnerRecommendations.map(t=>tagName(t.taxonomyId,boot)).join('、')||'先补充题目与有效标签'}。</Notice>}
 {preview&&preview.rejectedCandidates.length>0&&<details><summary>查看未纳入候选（{preview.rejectedCandidates.length}）</summary>{preview.rejectedCandidates.map((c,i)=><p key={i}>{c.candidateId?.split('||').at(-1)??'候选'}：{c.reason} · {c.detail}</p>)}</details>}</Panel>
 <Panel title="已保存计划"><ErrorNotice error={list.error}/><label>选择计划<select value={id??''} onChange={e=>setId(e.target.value||null)}><option value="">请选择</option>{list.data?.plans.map(p=><option key={p.planId} value={p.planId}>{p.title} · {p.status==='draft'?'草案':'已采用'} · {new Date(p.createdAt).toLocaleDateString()}</option>)}</select></label><div className="icpc-toolbar"><label className="icpc-check"><input type="checkbox" checked={reveal} onChange={e=>setReveal(e.target.checked)}/>显示计划中的算法提示</label><button onClick={update}>刷新计划</button></div><ErrorNotice error={detail.error}/>
 {plan?<><h3>{plan.title}</h3><Notice>{plan.horizonDays} 天，共 {plan.taskCount} 项 / {plan.totalPlannedMinutes} 分钟。候选不足而未安排 {plan.totalUnmetMinutes} 分钟。依据：{plan.evidence.level}；已尝试 {plan.evidence.attemptedDistinctTotal} 道题。</Notice><p className="icpc-muted">打卡只记录计划执行，不会把题目改成评测通过。</p>{plan.status==='draft'&&<button className="icpc-primary" disabled={action.busy} onClick={()=>{void action.run(async signal=>{await api.request('plan.adopt',{accountId,planId:plan.planId,expectedHash:plan.contentHash},signal);update();return true;});}}>采用这份计划</button>}{plan.tasks.map(task=><PlanTask key={task.taskId+'|'+plan.contentHash} task={task} plan={plan} onChange={update}/>)}</>:<Empty>选择一份草案或已采用的计划查看安排。</Empty>}</Panel>
 </>}</>;
}
