/**
 * Initial taxonomy, version 2026.09.1.
 *
 * Scope decisions:
 * - Only algorithm/technique knowledge lives here. Source names (Codeforces, Luogu…),
 *   contest/event names (ICPC, CCPC, NOI…), years and difficulty labels are intentionally
 *   **not** nodes: they must never appear in algorithm statistics. They are recognised as
 *   non-algorithm tags in `classify.ts` and preserved verbatim on the problem.
 * - Chinese and English spellings are both first-class aliases because personal records
 *   come from CF (English tags) and Luogu/Hydro (Chinese tags).
 * - Ids are permanent. Adding a node is a new taxonomy version; renaming an id is a
 *   migration, never an edit.
 */
import { createTaxonomy, type Taxonomy, type TaxonomyNode, type TaxonomyNodeKind } from './types.js';

export const TAXONOMY_V1_VERSION = '2026.09.1';

function node(
  id: string,
  parentId: string | null,
  kind: TaxonomyNodeKind,
  en: string,
  zh: string,
  aliases: readonly string[],
  description: string,
): TaxonomyNode {
  return { id, parentId, kind, names: { en, zh }, aliases, description };
}

const TECHNIQUES: readonly TaxonomyNode[] = [
  // Search / binary techniques ---------------------------------------------------------
  node('search', null, 'category', 'Search', '搜索与查找', ['search', '搜索'], 'Search and lookup families.'),
  node(
    'search.binary',
    'search',
    'technique',
    'Binary search',
    '二分查找',
    ['binary search', '二分', '二分查找', 'bisect'],
    'Monotone predicate search over a sorted domain.',
  ),
  node(
    'search.binary-answer',
    'search',
    'technique',
    'Binary search on answer',
    '二分答案',
    ['binary search on answer', '二分答案', 'parametric search'],
    'Search the answer space, checking feasibility per candidate.',
  ),
  node(
    'search.ternary',
    'search',
    'technique',
    'Ternary search',
    '三分',
    ['ternary search', '三分', '三分法'],
    'Unimodal extremum search.',
  ),
  node(
    'search.two-pointers',
    'search',
    'technique',
    'Two pointers',
    '双指针',
    ['two pointers', '双指针', 'two pointer'],
    'Monotone pointer sweep over a sequence.',
  ),
  node(
    'search.sliding-window',
    'search',
    'technique',
    'Sliding window',
    '滑动窗口',
    ['sliding window', '滑动窗口', '尺取法'],
    'Maintain an aggregate over a moving interval.',
  ),
  node(
    'search.meet-in-the-middle',
    'search',
    'technique',
    'Meet in the middle',
    '折半搜索',
    ['meet in the middle', '折半搜索', 'mitm'],
    'Split the search space and combine halves.',
  ),
  node(
    'search.traversal',
    'search',
    'technique',
    'DFS / BFS traversal',
    '深度优先与广度优先搜索',
    ['dfs', 'bfs', '深度优先搜索', '广度优先搜索', 'traversal'],
    'Graph/tree traversal as a search strategy.',
  ),
  node(
    'search.backtracking',
    'search',
    'technique',
    'Backtracking',
    '回溯',
    ['backtracking', '回溯', '剪枝', 'pruning'],
    'Exhaustive search with pruning.',
  ),
  node(
    'search.heuristic',
    'search',
    'technique',
    'Heuristic search',
    '启发式搜索',
    ['heuristic search', '启发式搜索', 'a star', 'ida star', '模拟退火', 'simulated annealing'],
    'Best-first / annealing style search when exact search is infeasible.',
  ),

  // Implementation ---------------------------------------------------------------------
  node('implementation', null, 'category', 'Implementation', '实现', ['implementation', '实现'], 'Implementation-flavoured tasks.'),
  node(
    'implementation.simulation',
    'implementation',
    'technique',
    'Simulation',
    '模拟',
    ['simulation', '模拟', '模拟题'],
    'Directly simulate the described process.',
  ),
  node(
    'implementation.constructive',
    'implementation',
    'technique',
    'Constructive',
    '构造',
    ['constructive', '构造', '构造题', 'construction'],
    'Build an object satisfying stated constraints.',
  ),
  node(
    'implementation.brute-force',
    'implementation',
    'technique',
    'Brute force / enumeration',
    '暴力枚举',
    ['brute force', '暴力', '枚举', 'enumeration'],
    'Enumerate candidates within the constraints.',
  ),
  node(
    'implementation.ad-hoc',
    'implementation',
    'technique',
    'Ad hoc',
    '思维题',
    ['ad hoc', '思维', '思维题', 'observation', '结论题'],
    'Problem-specific reasoning without a standard technique.',
  ),

  // Greedy -----------------------------------------------------------------------------
  node('greedy', null, 'category', 'Greedy', '贪心', ['greedy', '贪心', '贪心算法'], 'Greedy selection families.'),
  node(
    'greedy.exchange-argument',
    'greedy',
    'technique',
    'Exchange argument',
    '交换论证',
    ['exchange argument', '交换论证', '邻项交换', '排序贪心'],
    'Prove optimality by swapping adjacent choices.',
  ),
  node(
    'greedy.scheduling',
    'greedy',
    'technique',
    'Scheduling / deadline greedy',
    '期限调度贪心',
    ['scheduling', '调度贪心', 'deadline greedy', '反悔贪心', 'regret greedy'],
    'Deadline/priority-driven selection, optionally with regret.',
  ),

  // Dynamic programming ----------------------------------------------------------------
  node('dp', null, 'category', 'Dynamic programming', '动态规划', ['dp', 'dynamic programming', '动态规划', '动规'], 'Dynamic programming families.'),
  node('dp.knapsack', 'dp', 'technique', 'Knapsack', '背包', ['knapsack', '背包', '01背包', '完全背包'], 'Capacity/weight selection DP.'),
  node('dp.interval', 'dp', 'technique', 'Interval DP', '区间 DP', ['interval dp', '区间dp', '区间动态规划'], 'DP over contiguous ranges.'),
  node('dp.tree', 'dp', 'technique', 'Tree DP', '树形 DP', ['tree dp', '树形dp', '树上dp'], 'DP over a rooted tree.'),
  node('dp.bitmask', 'dp', 'technique', 'Bitmask DP', '状压 DP', ['bitmask dp', '状压dp', '状态压缩', '状态压缩dp'], 'DP whose state is a bit set.'),
  node('dp.digit', 'dp', 'technique', 'Digit DP', '数位 DP', ['digit dp', '数位dp', 'digital dp'], 'DP over digit positions with bounds.'),
  node(
    'dp.sos',
    'dp',
    'technique',
    'Subset-sum / SOS DP',
    '子集和与高维前缀和',
    ['sos dp', 'subset sum', '子集和', '高维前缀和'],
    'Aggregate over subsets or dimensions.',
  ),
  node(
    'dp.state-machine',
    'dp',
    'technique',
    'State machine DP',
    '状态机 DP',
    ['state machine dp', '状态机', '状态机dp'],
    'DP over explicit states with transitions.',
  ),
  node(
    'dp.optimization',
    'dp',
    'technique',
    'DP optimization',
    'DP 优化',
    ['dp optimization', '斜率优化', '决策单调性', 'convex hull trick', '单调队列优化'],
    'Monotonicity/convexity based transition speedups.',
  ),

  // Data structures --------------------------------------------------------------------
  node('data-structure', null, 'category', 'Data structures', '数据结构', ['data structure', '数据结构'], 'Data structure families.'),
  node(
    'data-structure.prefix-sum',
    'data-structure',
    'technique',
    'Prefix sums',
    '前缀和',
    ['prefix sum', '前缀和', 'prefix sums'],
    'Precomputed cumulative aggregates.',
  ),
  node(
    'data-structure.difference-array',
    'data-structure',
    'technique',
    'Difference array',
    '差分',
    ['difference array', '差分', '树上差分'],
    'Range updates via boundary deltas.',
  ),
  node(
    'data-structure.dsu',
    'data-structure',
    'technique',
    'Disjoint set union',
    '并查集',
    ['dsu', 'union find', '并查集', '带权并查集'],
    'Merge/find connectivity structure.',
  ),
  node(
    'data-structure.bit',
    'data-structure',
    'technique',
    'Fenwick tree',
    '树状数组',
    ['fenwick', 'fenwick tree', '树状数组', 'bit'],
    'Prefix aggregation with point updates.',
  ),
  node(
    'data-structure.segment-tree',
    'data-structure',
    'technique',
    'Segment tree',
    '线段树',
    ['segment tree', '线段树', 'segtree'],
    'Range query/update over a static layout.',
  ),
  node(
    'data-structure.segment-tree-lazy',
    'data-structure',
    'technique',
    'Lazy propagation',
    '线段树懒标记',
    ['lazy propagation', '懒标记', 'lazy segment tree'],
    'Deferred range updates in a segment tree.',
  ),
  node(
    'data-structure.sparse-table',
    'data-structure',
    'technique',
    'Sparse table / RMQ',
    'ST 表与 RMQ',
    ['sparse table', 'st表', 'rmq'],
    'Idempotent static range queries.',
  ),
  node(
    'data-structure.balanced-bst',
    'data-structure',
    'technique',
    'Balanced BST',
    '平衡树',
    ['balanced bst', '平衡树', 'treap', 'splay', 'fhq treap'],
    'Ordered set with logarithmic operations.',
  ),
  node(
    'data-structure.heap',
    'data-structure',
    'technique',
    'Heap / priority queue',
    '堆与优先队列',
    ['heap', '堆', '优先队列', 'priority queue'],
    'Extremal element extraction, including mergeable heaps.',
  ),
  node(
    'data-structure.monotonic-stack',
    'data-structure',
    'technique',
    'Monotonic stack / queue',
    '单调栈与单调队列',
    ['monotonic stack', '单调栈', '单调队列', 'monotonic queue'],
    'Amortised nearest-greater style structures.',
  ),
  node(
    'data-structure.sqrt-decomposition',
    'data-structure',
    'technique',
    'Sqrt decomposition',
    '分块',
    ['sqrt decomposition', '分块', 'block decomposition'],
    'Block-based decomposition balancing update/query cost.',
  ),
  node(
    'data-structure.persistent',
    'data-structure',
    'technique',
    'Persistent structures',
    '可持久化数据结构',
    ['persistent data structure', '可持久化', '主席树', 'chairman tree'],
    'Versioned structures retaining history.',
  ),

  // Graph theory -----------------------------------------------------------------------
  node('graph', null, 'category', 'Graph theory', '图论', ['graph', '图论', 'graph theory'], 'Graph algorithms.'),
  node(
    'graph.shortest-path',
    'graph',
    'technique',
    'Shortest path',
    '最短路',
    ['shortest path', '最短路', 'dijkstra', 'spfa', 'bellman ford', 'floyd'],
    'Single-source / all-pairs shortest paths.',
  ),
  node(
    'graph.topological-sort',
    'graph',
    'technique',
    'Topological sort',
    '拓扑排序',
    ['topological sort', '拓扑排序', 'topsort'],
    'Linear extension of a DAG.',
  ),
  node(
    'graph.scc',
    'graph',
    'technique',
    'Strongly connected components',
    '强连通分量',
    ['scc', 'strongly connected components', '强连通分量', 'tarjan', '缩点'],
    'Condense directed cycles.',
  ),
  node(
    'graph.bridges-articulation',
    'graph',
    'technique',
    'Bridges and articulation points',
    '割边与割点',
    ['bridge', 'cut vertex', '割点', '割边', 'articulation point'],
    'Cut structure of an undirected graph.',
  ),
  node(
    'graph.tree',
    'graph',
    'technique',
    'Tree algorithms',
    '树上算法',
    ['tree algorithm', '树上问题', '树的遍历', 'tree dfs'],
    'Rooted-tree traversals and subtree aggregates.',
  ),
  node(
    'graph.lca',
    'graph',
    'technique',
    'Lowest common ancestor',
    '最近公共祖先',
    ['lca', 'lowest common ancestor', '最近公共祖先', '倍增'],
    'Ancestor queries on a rooted tree.',
  ),
  node(
    'graph.tree-diameter',
    'graph',
    'technique',
    'Tree diameter / rerooting',
    '树的直径与换根',
    ['tree diameter', '树的直径', 'rerooting', '换根dp'],
    'Longest path and rerooting aggregates.',
  ),

  // Flow and matching ------------------------------------------------------------------
  node('flow', null, 'category', 'Network flow', '网络流', ['network flow', '网络流', 'flow'], 'Flow formulations.'),
  node(
    'flow.max-flow',
    'flow',
    'technique',
    'Maximum flow',
    '最大流',
    ['max flow', '最大流', 'dinic', 'isap'],
    'Maximum flow value under capacities.',
  ),
  node('flow.min-cut', 'flow', 'technique', 'Minimum cut', '最小割', ['min cut', '最小割'], 'Cut dual of maximum flow.'),
  node(
    'flow.min-cost-flow',
    'flow',
    'technique',
    'Min-cost flow',
    '费用流',
    ['min cost flow', '费用流', 'mcmf'],
    'Flow with a cost objective.',
  ),
  node(
    'matching',
    null,
    'category',
    'Matching',
    '匹配',
    ['matching', '匹配'],
    'Matching problems and theorems.',
  ),
  node(
    'matching.bipartite',
    'matching',
    'technique',
    'Bipartite matching',
    '二分图匹配',
    ['bipartite matching', '二分图匹配', 'hungarian', '匈牙利算法', 'kuhn'],
    'Matching in bipartite graphs.',
  ),
  node(
    'matching.general',
    'matching',
    'technique',
    'General graph matching',
    '一般图匹配',
    ['general matching', '一般图匹配', 'blossom', '带花树'],
    'Matching in general graphs.',
  ),
  node(
    'matching.hall',
    'matching',
    'technique',
    'Hall / König theorems',
    '霍尔与柯尼希定理',
    ['hall theorem', '霍尔定理', 'konig', '柯尼希定理'],
    'Structural theorems used to avoid explicit flow.',
  ),

  // Strings ----------------------------------------------------------------------------
  node('strings', null, 'category', 'Strings', '字符串', ['string', '字符串', 'strings'], 'String algorithms.'),
  node(
    'strings.kmp',
    'strings',
    'technique',
    'KMP / prefix function',
    'KMP 与前缀函数',
    ['kmp', 'prefix function', '前缀函数', 'fail 树'],
    'Border structure of a pattern.',
  ),
  node(
    'strings.z-algorithm',
    'strings',
    'technique',
    'Z-algorithm / exKMP',
    'Z 函数与扩展 KMP',
    ['z algorithm', 'z函数', '扩展kmp', 'exkmp'],
    'Longest common prefix computations.',
  ),
  node(
    'strings.hashing',
    'strings',
    'technique',
    'String hashing',
    '字符串哈希',
    ['string hashing', '字符串哈希', 'rolling hash', 'hash'],
    'Probabilistic equality of substrings.',
  ),
  node(
    'strings.trie',
    'strings',
    'technique',
    'Trie',
    '字典树',
    ['trie', '字典树', '前缀树'],
    'Prefix tree over a key set.',
  ),
  node(
    'strings.ac-automaton',
    'strings',
    'technique',
    'Aho–Corasick automaton',
    'AC 自动机',
    ['aho corasick', 'ac自动机', 'acam'],
    'Multi-pattern matching automaton.',
  ),
  node(
    'strings.suffix-array',
    'strings',
    'technique',
    'Suffix array',
    '后缀数组',
    ['suffix array', '后缀数组', 'sa', 'height 数组'],
    'Sorted suffix structure.',
  ),
  node(
    'strings.suffix-automaton',
    'strings',
    'technique',
    'Suffix automaton',
    '后缀自动机',
    ['suffix automaton', '后缀自动机', 'sam'],
    'Minimal DFA of all substrings.',
  ),
  node(
    'strings.manacher',
    'strings',
    'technique',
    'Manacher',
    'Manacher 算法',
    ['manacher', '马拉车', '回文串', 'palindrome'],
    'Linear-time palindromic radius computation.',
  ),

  // Mathematics ------------------------------------------------------------------------
  node('math', null, 'category', 'Mathematics', '数学', ['math', '数学'], 'Mathematical techniques.'),
  node('math.number-theory', 'math', 'category', 'Number theory', '数论', ['number theory', '数论'], 'Integer arithmetic structures.'),
  node(
    'math.number-theory.gcd',
    'math.number-theory',
    'technique',
    'GCD / extended Euclid',
    '最大公约数与扩展欧几里得',
    ['gcd', 'exgcd', '扩展欧几里得', '裴蜀定理', 'bezout'],
    'Divisibility and linear Diophantine equations.',
  ),
  node(
    'math.number-theory.prime-sieve',
    'math.number-theory',
    'technique',
    'Prime sieve / factoring',
    '素数筛与质因数分解',
    ['sieve', '素数筛', '线性筛', '埃氏筛', 'factorization', '质因数分解'],
    'Enumerate primes and factor integers.',
  ),
  node(
    'math.number-theory.modular-inverse',
    'math.number-theory',
    'technique',
    'Modular inverse',
    '模逆元',
    ['modular inverse', '逆元', '费马小定理', 'fermat little theorem'],
    'Division in modular arithmetic.',
  ),
  node(
    'math.number-theory.crt',
    'math.number-theory',
    'technique',
    'Chinese remainder theorem',
    '中国剩余定理',
    ['crt', 'chinese remainder theorem', '中国剩余定理', 'excrt'],
    'Combine congruences modulo coprime (or general) moduli.',
  ),
  node(
    'math.number-theory.mobius',
    'math.number-theory',
    'technique',
    'Möbius inversion',
    '莫比乌斯反演',
    ['mobius', '莫比乌斯反演', '整除分块', '数论分块'],
    'Inversion over divisor lattices.',
  ),
  node('math.combinatorics', 'math', 'category', 'Combinatorics', '组合数学', ['combinatorics', '组合数学', '计数'], 'Counting techniques.'),
  node(
    'math.combinatorics.inclusion-exclusion',
    'math.combinatorics',
    'technique',
    'Inclusion–exclusion',
    '容斥原理',
    ['inclusion exclusion', '容斥', '容斥原理'],
    'Alternating sums over intersections.',
  ),
  node(
    'math.combinatorics.catalan',
    'math.combinatorics',
    'technique',
    'Catalan / binomial identities',
    '卡特兰数与组合恒等式',
    ['catalan', '卡特兰数', 'binomial', '组合数'],
    'Standard counting sequences and identities.',
  ),
  node(
    'math.combinatorics.lucas',
    'math.combinatorics',
    'technique',
    'Lucas / Stirling numbers',
    '卢卡斯定理与斯特林数',
    ['lucas', '卢卡斯定理', 'stirling', '斯特林数'],
    'Binomial coefficients modulo primes; set partitions.',
  ),
  node(
    'math.linear-algebra',
    'math',
    'category',
    'Linear algebra',
    '线性代数',
    ['linear algebra', '线性代数', '矩阵'],
    'Matrix and vector algebra.',
  ),
  node(
    'math.linear-algebra.matrix-power',
    'math.linear-algebra',
    'technique',
    'Matrix exponentiation',
    '矩阵快速幂',
    ['matrix exponentiation', '矩阵快速幂', '矩阵乘法'],
    'Linear recurrences via matrix powers.',
  ),
  node(
    'math.linear-algebra.gaussian-elimination',
    'math.linear-algebra',
    'technique',
    'Gaussian elimination',
    '高斯消元',
    ['gaussian elimination', '高斯消元', '线性方程组'],
    'Solve linear systems over a field.',
  ),
  node(
    'math.linear-algebra.linear-basis',
    'math.linear-algebra',
    'technique',
    'Linear basis',
    '线性基',
    ['linear basis', '线性基', 'xor basis'],
    'Span of XOR vectors.',
  ),
  node(
    'math.probability',
    'math',
    'technique',
    'Probability',
    '概率',
    ['probability', '概率', '概率dp', '概率期望'],
    'Probability computations and DP.',
  ),
  node(
    'math.expected-value',
    'math',
    'technique',
    'Expected value',
    '期望',
    ['expected value', '期望', '期望dp', 'linearity of expectation'],
    'Expectation via linearity or DP.',
  ),
  node(
    'math.game-theory',
    'math',
    'technique',
    'Game theory',
    '博弈论',
    ['game theory', '博弈论', '博弈', 'sg函数', 'nim', 'sprague grundy'],
    'Impartial/combinatorial games.',
  ),
  node(
    'math.fft',
    'math',
    'technique',
    'FFT / NTT convolution',
    '快速傅里叶变换与卷积',
    ['fft', 'ntt', '卷积', 'convolution', '快速傅里叶变换'],
    'Polynomial multiplication and convolution.',
  ),

  // Geometry ---------------------------------------------------------------------------
  node('geometry', null, 'category', 'Computational geometry', '计算几何', ['geometry', '计算几何', '几何'], 'Geometric algorithms.'),
  node(
    'geometry.basic',
    'geometry',
    'technique',
    'Vectors and cross products',
    '向量与叉积',
    ['vector', '向量', '叉积', 'cross product', '点积'],
    'Orientation and area primitives.',
  ),
  node(
    'geometry.convex-hull',
    'geometry',
    'technique',
    'Convex hull',
    '凸包',
    ['convex hull', '凸包', 'graham', 'andrew'],
    'Hull of a point set.',
  ),
  node(
    'geometry.sweep-line',
    'geometry',
    'technique',
    'Sweep line',
    '扫描线',
    ['sweep line', '扫描线'],
    'Event-ordered geometric processing.',
  ),
  node(
    'geometry.rotating-calipers',
    'geometry',
    'technique',
    'Rotating calipers',
    '旋转卡壳',
    ['rotating calipers', '旋转卡壳'],
    'Diameter/width of a convex polygon.',
  ),
  node(
    'geometry.half-plane',
    'geometry',
    'technique',
    'Half-plane intersection',
    '半平面交',
    ['half plane intersection', '半平面交'],
    'Intersection of half-planes.',
  ),

  // Offline techniques -----------------------------------------------------------------
  node('offline', null, 'category', 'Offline techniques', '离线技巧', ['offline', '离线', '离线技巧'], 'Query reordering and divide-and-conquer offline.'),
  node(
    'offline.mo',
    'offline',
    'technique',
    "Mo's algorithm",
    '莫队',
    ['mo algorithm', '莫队', "mo's algorithm", '带修莫队'],
    'Query reordering with incremental state.',
  ),
  node(
    'offline.cdq-divide',
    'offline',
    'technique',
    'CDQ divide and conquer',
    'CDQ 分治',
    ['cdq divide and conquer', 'cdq分治', 'cdq'],
    'Contribution counting over index/order.',
  ),
  node(
    'offline.parallel-binary-search',
    'offline',
    'technique',
    'Parallel binary search',
    '整体二分',
    ['parallel binary search', '整体二分', '整体二分答案'],
    'Batch monotone queries solved together.',
  ),

  // Cross-cutting tricks ---------------------------------------------------------------
  node('tricks', null, 'category', 'Techniques & tricks', '技巧', ['trick', '技巧', '杂项'], 'Cross-cutting implementation tricks.'),
  node(
    'tricks.bitwise',
    'tricks',
    'technique',
    'Bitwise operations',
    '位运算',
    ['bitwise', 'bitwise operations', '位运算', 'bit trick', 'lowbit'],
    'Bit-level manipulation and tricks.',
  ),
  node(
    'tricks.discretization',
    'tricks',
    'technique',
    'Coordinate compression',
    '离散化',
    ['coordinate compression', '离散化'],
    'Map large coordinates onto a dense range.',
  ),
  node(
    'tricks.small-to-large',
    'tricks',
    'technique',
    'Small-to-large merging',
    '启发式合并',
    ['small to large', '启发式合并', 'dsu on tree'],
    'Merge smaller containers into larger ones.',
  ),
  node(
    'tricks.randomization',
    'tricks',
    'technique',
    'Randomization',
    '随机化',
    ['randomization', '随机化', '哈希冲突', 'schwartz zippel'],
    'Randomised algorithms and hashing arguments.',
  ),
  node(
    'tricks.interactive',
    'tricks',
    'technique',
    'Interactive problems',
    '交互题',
    ['interactive', '交互题', '交互'],
    'Problems driven by judge queries.',
  ),
];

/** Frozen initial taxonomy. */
export const TAXONOMY_V1: Taxonomy = createTaxonomy({ version: TAXONOMY_V1_VERSION, nodes: TECHNIQUES });

/**
 * The current vocabulary (`CURRENT_TAXONOMY`) lives in `v2.ts`. `TAXONOMY_V1` stays frozen so
 * snapshots pinned to 2026.09.1 keep resolving against exactly these nodes.
 */
